---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    component: postgres
spec:
  selector:
    component: postgres
  type: ClusterIP
  ports:
    - name: tcp-5432
      protocol: TCP
      port: 5432
      targetPort: 5432
