---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: postgres
  labels:
    app: postgres
    comp: postgres
spec:
  selector:
    app: postgres
    comp: postgres
  type: ClusterIP
  ports:
    - name: tcp-5432
      protocol: TCP
      port: 5432
      targetPort: 5432
